<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BambuMCPSharp</RootNamespace>
    <AssemblyName>BambuMCPSharp</AssemblyName>
    <ApplicationIcon>wmcp.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BambuLab.X1Camera" />
    <PackageReference Include="BambuLab.X1Camera.Imaging" />
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Process" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wmcp.ico" LogicalName="MCPSharp.wmcp.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="BambuMCPSharp.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="BambuMCPSharp.*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <DependentUpon>BambuMCPSharp.json</DependentUpon>
    </None>
  </ItemGroup>

</Project>
